<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use YireoTraining\ExampleLokiComponents\Component\Comments\CommentsViewModel;
use Yireo\LokiComponents\Util\ComponentUtil;

/** @var Template $block */
/** @var CommentsViewModel $viewModel */
/** @var ComponentUtil $componentUtil */
?>
<div id="<?= $componentUtil->getElementIdByBlock($block) ?>">
    Comments counter: <?= count($viewModel->getComments()) ?>
</div>
