<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use YireoTraining\ExampleLokiComponents\Component\Comments\CommentsViewModel;
use Yireo\LokiComponents\Util\ComponentUtil;

/** @var Template $block */
/** @var CommentsViewModel $viewModel */
/** @var ComponentUtil $componentUtil */
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('ExampleLokiComponentsComments', () => ({
            ...LokiComponentType,
            blockId: '<?= $block->getNameInLayout() ?>',
            target: '<?= $viewModel->getTargetString() ?>',
            remove(event) {
                this.post({
                    task: 'remove',
                    comment: event.target.getAttribute('data-comment')
                });
            }
        }));
    });
</script>
