<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\LokiComponents\Component\ComponentViewModel;
use Yireo\LokiComponents\Factory\ViewModelFactory;

/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ComponentViewModel $viewModel */

?>
<div class="my-4">
        <button @click="post" class="btn btn-primary">
            Exception test
        </button>
</div>
