<?php
declare(strict_types=1);

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\View\Element\Template;
use Loki\Components\Component\ComponentViewModel;
use Loki\Components\Factory\ViewModelFactory;

/** @version 0.0.14 */
/** @var CssClass $css */
/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ComponentViewModel $viewModel */

?>
<div class="<?= /* @noEscape */ $css('my-4') ?>">
    <button @click="post" class="<?= /* @noEscape */ $css('btn btn-primary', 'button') ?>">
        Exception test
    </button>
</div>
