<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\LokiComponents\Component\ComponentViewModel;

/** @var Template $block */
/** @var ComponentViewModel $viewModel */

$isAjax = $viewModel->getContext()->isAjax();
?>
<div class="my-4">
    <?php if ($viewModel->getValue()): ?>
        <button @click="toggle" class="btn btn-primary" <?php if ($isAjax): ?>x-autofocus<?php endif; ?>>
            Unlike
        </button>
    <?php else: ?>
        <button @click="toggle" class="btn btn-primary" <?php if ($isAjax): ?>x-autofocus<?php endif; ?>>
            Like
        </button>
    <?php endif; ?>
</div>
