<?php
declare(strict_types=1);

/** @version 0.0.10 */

use Magento\Framework\View\Element\Template;
use Loki\Components\Component\ComponentViewModel;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Components\Util\Ajax;

/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ComponentViewModel $viewModel */

$ajax = $viewModelFactory->create(Ajax::class);
$isAjax = $ajax->isAjax();
?>
<div class="<?= $css('my-4', '@todo') ?>">
    <?php if ($viewModel->getValue()): ?>
        <button @click="toggle" class="<?= $css('btn btn-primary', '@todo') ?>" <?php if ($isAjax): ?>x-autofocus<?php endif; ?>>
            Unlike
        </button>
    <?php else: ?>
        <button @click="toggle" class="<?= $css('btn btn-primary', '@todo') ?>" <?php if ($isAjax): ?>x-autofocus<?php endif; ?>>
            Like
        </button>
    <?php endif; ?>
</div>
