<?php
declare(strict_types=1);

/** @version 0.0.12 */

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\View\Element\Template;
use Loki\Components\Component\ComponentViewModel;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Components\Util\Ajax;

/** @var CssClass $css */
/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ComponentViewModel $viewModel */

$ajax = $viewModelFactory->create(Ajax::class);
$isAjax = $ajax->isAjax();
?>
<div class="<?= /* @noEscape */ $css('my-4') ?>">
    <?php if ($viewModel->getValue()): ?>
        <button
            @click="toggle"
            class="<?= /* @noEscape */ $css('btn btn-primary', 'button') ?>"
            <?php if ($isAjax): ?>x-autofocus<?php endif; ?>
        >
            Unlike
        </button>
    <?php else: ?>
        <button
            @click="toggle"
            class="<?= /* @noEscape */ $css('btn btn-primary', 'button') ?>"
            <?php if ($isAjax): ?>x-autofocus<?php endif; ?>
        >
            Like
        </button>
    <?php endif; ?>
</div>
