<?php
declare(strict_types=1);

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\View\Element\Template;

/** @version 0.0.14 */
/** @var CssClass $css */
/** @var Template $block */
?>
<div class="<?= $escaper->escapeHtmlAttr($css('')) ?>">
    <h1 class="text-2xl">Modal examples</h1>

    <div class="<?= $escaper->escapeHtmlAttr($css('my-8 modal-examples flex flex-col gap-4')) ?>">
        <?= /* @noEscape */ $block->getChildHtml() ?>
    </div>
</div>
