<?php
declare(strict_types=1);

/** @version 0.0.10 */

use Magento\Framework\View\Element\Template;
use Loki\Components\Factory\ViewModelFactory;
use YireoTraining\ExampleLokiComponents\ViewModel\ExampleListing;

/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ExampleListing $exampleListing */

$exampleListing = $viewModelFactory->create(ExampleListing::class);
?>
<div class="<?= /* @noEscape */
$css('loki', '@todo') ?>">
    <h1 class="<?= /* @noEscape */
$css('text-3xl', '@todo') ?>">Yireo Loki Components Examples</h1>

    <ul class="<?= /* @noEscape */
$css('list-disc pl-4', '@todo') ?>">
        <?php foreach ($exampleListing->getLinks() as $link): ?>
            <li>
                <a class="<?= /* @noEscape */
$css('hover:text-sky-500', '@todo') ?>" href="<?= /* @noEscape */ $block->getUrl($link['url']) ?>"><?= $link['label'] ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
