<?php
declare(strict_types=1);

/** @version 0.0.10 */

use Magento\Framework\View\Element\Template;
use Loki\Components\Factory\ViewModelFactory;
use YireoTraining\ExampleLokiComponents\ViewModel\ExampleListing;

/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ExampleListing $exampleListing */

$exampleListing = $viewModelFactory->create(ExampleListing::class);
?>
<div class="<?= $css('loki', '@todo') ?>">
    <div class="<?= $css('pr-16', '@todo') ?>">
        <h2 class="<?= $css('text-md leading-5 font-semibold uppercase', '@todo') ?>">Loki Components</h2>

        <ul class="<?= $css('mt-4', '@todo') ?>">
            <?php foreach ($exampleListing->getLinks() as $link): ?>
                <li>
                    <a class="<?= $css('text-base leading-10', '@todo') ?>" href="<?= /* @noEscape */ $block->getUrl($link['url']) ?>"><?= $link['label'] ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
