<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */

$links = [
    'random' => 'Random number',
    'like' => 'Like/Unlike toggle',
    'switcher' => 'Template toggle',
    'comments' => 'Comments form and listing',
    'notification' => 'Notifications',
];
?>
<h1 class="text-3xl">Yireo Loki Components</h1>

<ul class="list-disc pl-4">
    <?php foreach ($links as $linkName => $linkTitle): ?>
        <li>
            <a class="hover:text-sky-500" href="<?= $block->getUrl('loki_example_components/example/'.$linkName) ?>"><?= $linkTitle ?></a>
        </li>
    <?php endforeach; ?>
</ul>
