<?php
declare(strict_types=1);

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\View\Element\Template;
use Loki\Components\Factory\ViewModelFactory;
use YireoTraining\ExampleLokiComponents\ViewModel\ExampleListing;

/** @version 0.0.15 */
/** @var CssClass $css */
/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ExampleListing $exampleListing */

$exampleListing = $viewModelFactory->create(ExampleListing::class);
?>
<div class="<?= $escaper->escapeHtmlAttr($css('loki')) ?>">
    <div class="<?= $escaper->escapeHtmlAttr($css('pr-16', 'inner')) ?>">
        <h2 class="<?= $escaper->escapeHtmlAttr($css('text-md leading-5 font-semibold uppercase', 'header')) ?>">
            Loki Components
        </h2>

        <ul class="<?= $escaper->escapeHtmlAttr($css('mt-4', 'listing')) ?>">
            <?php foreach ($exampleListing->getLinks() as $link): ?>
                <li>
                    <a
                        class="<?= $escaper->escapeHtmlAttr($css('text-base leading-10', 'anchor')) ?>"
                        href="<?= $escaper->escapeUrl($block->getUrl($link['url'])) ?>">
                        <?= $link['label'] ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
