<?php
declare(strict_types=1);

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\View\Element\Template;
use Loki\Components\Factory\ViewModelFactory;
use YireoTraining\ExampleLokiComponents\ViewModel\ExampleListing;

/** @version 0.0.18 */
/** @var CssClass $css */
/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ExampleListing $exampleListing */

$exampleListing = $viewModelFactory->create(ExampleListing::class);
?>
<div class="<?= $escaper->escapeHtmlAttr($css('loki')) ?>">
    <h1 class="<?= $escaper->escapeHtmlAttr($css('text-3xl', 'heading')) ?>">
        Yireo Loki Components Examples
    </h1>

    <ul class="<?= $escaper->escapeHtmlAttr($css('list-disc pl-4', 'listing')) ?>">
        <?php foreach ($exampleListing->getLinks() as $link): ?>
            <li>
                <a
                    class="<?= $escaper->escapeHtmlAttr($css('hover:text-sky-500', 'anchor')) ?>"
                    href="<?= $escaper->escapeUrl($block->getUrl($link['url'])) ?>"
                >
                    <?= $escaper->escapeHtml($link['label']) ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
