<?php
declare(strict_types=1);

/** @version 0.0.14 */

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var CssClass $css */
?>
<div class="<?= /* @noEscape */ $css('my-4') ?>">
    Random number: <?= $escaper->escapeHtml(rand()) ?><br/>
    <button @click="post" class="btn btn-primary">Refresh</button>
</div>
