<?php
declare(strict_types=1);

use Loki\Components\Util\Block\TemplateRenderer;
use Loki\CssUtils\Util\CssClass;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\Components\Component\ComponentViewModel;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Components\Util\Block\ImageRenderer;

/** @version 0.0.17 */
/** @var TemplateRenderer $imageRenderer */
/** @var TemplateRenderer $templateRenderer */
/** @var CssClass $css */
/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ComponentViewModel $viewModel */
/** @var ImageRenderer $imageRenderer */

?>
<div class="<?= $escaper->escapeHtmlAttr($css('')) ?>">
    <p>Value: <span x-html="value"></span></p>

    <button
        @click="toggleModal"
        class="<?= $escaper->escapeHtmlAttr($css('btn btn-primary', 'button')) ?>"
        :disabled="isModalOpen"
    >
        <span x-cloak x-show="isModalOpen">Close Drawer Left</span>
        <span x-show="isModalClosed">Open Drawer Left</span>
    </button>

    <dialog
        x-ref="modal"
        class="<?= $escaper->escapeHtmlAttr($css(
            'drawer drawer-left relative bg-inherit m-0 w-full h-full', 'dialog'
        )) ?>"
    >
        <div class="<?= $escaper->escapeHtmlAttr($css('bg-white w-1/2 h-full p-10', 'dialog-inner')) ?>">
            <button
                @click="toggleModal"
                class="<?= $escaper->escapeHtmlAttr($css('float-right cursor-pointer w-4', 'close-button')) ?>"
            >
                <?= /* @noEscape */ $imageRenderer->icon($block, 'xmark') ?>
            </button>

            <div class="<?= $escaper->escapeHtmlAttr($css('p-4 grid gap-4', 'dialog-inner')) ?>">
                <?= /* @noEscape */ $templateRenderer->html(
                    $block, 'YireoTraining_ExampleLokiComponents::modal/content.phtml'
                ) ?>

                <?= /* @noEscape */ $templateRenderer->html(
                    $block,
                    'Loki_Components::component/modal/close-button.phtml', [
                    'label' => 'Close Drawer'
                ]
                ) ?>
            </div>
        </div>
    </dialog>
</div>

