<?php
declare(strict_types=1);

/** @version 0.0.14 */

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\Components\Component\ComponentViewModel;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Components\Util\Block\ImageRenderer;

/** @var CssClass $css */
/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ComponentViewModel $viewModel */
/** @var ImageRenderer $imageRenderer */


?>
<div class="<?= /* noEscape */
/* @noEscape */
$css('') ?>">
    <p>Value: <span x-html="value"></span></p>

    <button
        @click="toggleModal"
        class="<?= /* noEscape */
        /* @noEscape */
        $css('btn btn-primary', 'button') ?>"
        :disabled="isModalOpen"
    >
        <span x-cloak x-show="isModalOpen">Close Drawer Left</span>
        <span x-show="isModalClosed">Open Drawer Left</span>
    </button>

    <dialog
        x-ref="modal"
        class="<?= /* noEscape */
        /* @noEscape */
        $css(
            'drawer drawer-left relative bg-inherit m-0 w-full h-full', 'dialog'
        ) ?>"
    >
        <div class="<?= /* noEscape */
        /* @noEscape */
        $css('bg-white w-1/2 h-full p-10', 'dialog-inner') ?>">
            <button
                @click="toggleModal"
                class="<?= /* noEscape */
                /* @noEscape */
                $css('float-right cursor-pointer w-4', 'close-button') ?>"
            >
                <?= /* @noEscape */
                $imageRenderer->icon($block, 'xmark') ?>
            </button>

            <div class="<?= $css('p-4 grid gap-4', 'dialog-inner') ?>">
                <?= $templateRenderer->html(
                    $block, 'YireoTraining_ExampleLokiComponents::modal/content.phtml'
                ) ?>

                <?= $templateRenderer->html(
                    $block,
                    'Loki_Components::component/modal/close-button.phtml', [
                    'label' => 'Close Drawer'
                ]
                ) ?>
            </div>
        </div>
    </dialog>
</div>

