<?php
declare(strict_types=1);

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\Components\Component\ComponentViewModel;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Components\Util\Block\ImageRenderer;

/** @version 0.0.14 */
/** @var CssClass $css */
/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ComponentViewModel $viewModel */
/** @var ImageRenderer $imageRenderer */

?>
<div class="<?= /* noEscape */
/* @noEscape */
$css('') ?>">
    <p>Value: <span x-html="value"></span></p>

    <button
        @click="toggleModal"
        class="<?= /* noEscape */
        /* @noEscape */
        $css('btn btn-primary', 'button') ?>"
        :disabled="isModalOpen">
        <span x-cloak x-show="isModalOpen">Close Drawer Right</span>
        <span x-show="isModalClosed">Open Drawer Right</span>
    </button>

    <dialog
        x-ref="modal"
        class="<?= /* noEscape */
        /* @noEscape */
        $css(
            'drawer-right relative bg-inherit m-0 w-full h-full inset-0',
            'dialog'
        ) ?>"
    >
        <div class="<?= /* noEscape */
        /* @noEscape */
        $css(
            'modal-inner bg-white w-1/4 h-full fixed right-0 p-10',
            'dialog-inner'
        ) ?>">
            <?= $templateRenderer->html(
                $block, 'Loki_Components::component/modal/close.phtml'
            ) ?>

            <div class="<?= $css('p-4 grid gap-4', 'dialog-inner') ?>">
                <?= $templateRenderer->html(
                    $block,
                    'YireoTraining_ExampleLokiComponents::modal/content.phtml'
                ) ?>

                <?= $templateRenderer->html(
                    $block,
                    'Loki_Components::component/modal/close-button.phtml', [
                        'label' => 'Close Drawer'
                    ]
                ) ?>
            </div>
        </div>
    </dialog>
</div>

