<?php
declare(strict_types=1);

/** @version 0.0.13 */

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\Components\Component\ComponentViewModel;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Field\ViewModel\ImageOutput;

/** @var CssClass $css */
/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ComponentViewModel $viewModel */
/** @var ImageOutput */
$imageOutput = $viewModelFactory->create(ImageOutput::class);
?>
<div class="<?= /* noEscape */
/* @noEscape */ $css('my-4') ?>">
    <p>Value: <span x-html="value"></span></p>

    <button
        @click="toggleModal"
        class="<?= /* noEscape */
/* @noEscape */ $css('btn btn-primary', 'button') ?>"
        :disabled="isModalOpen">
        <span x-cloak x-show="isModalOpen">Close Drawer Right</span>
        <span x-show="isModalClosed">Open Drawer Right</span>
    </button>

    <dialog
        x-ref="modal"
        class="<?= /* noEscape */
/* @noEscape */ $css('modal4 relative bg-inherit m-0 w-full h-full inset-0', 'dialog') ?>"
    >
        <div class="<?= /* noEscape */
/* @noEscape */ $css('modal-inner bg-white w-1/4 h-full fixed right-0 p-10', 'dialog-inner') ?>">
            <button
                @click="toggleModal"
                class="<?= /* noEscape */
/* @noEscape */ $css('float-right cursor-pointer w-4', 'close-button') ?>"
            >
                <?= /* @noEscape */ $imageOutput->get('Loki_Components::images/xmark.svg') ?>
            </button>

            <p class="<?= /* noEscape */
/* @noEscape */ $css('my-4', 'dialog-content') ?>">
                Input your text here
            </p>

            <input
                type="text"
                :value="value"
                @change="setValue"
                class="<?= /* noEscape */
/* @noEscape */ $css('form-input', 'dialog-input') ?>"
            />

            <button
                @click="toggleModal"
                class="<?= /* noEscape */
/* @noEscape */ $css('btn btn-primary mt-4', 'dialog-button') ?>"
            >
                <span>Close Drawer</span>
            </button>
        </div>
    </dialog>

    <style>
        @keyframes modal4-dialog {
            from {
                right: -800px;
            }
            to {
                right: 0;
            }
        }

        .modal4[open] .modal-inner {
            animation: modal4-dialog 500ms;
        }
    </style>
</div>

