<?php
declare(strict_types=1);

use Loki\Components\Util\Block\TemplateRenderer;
use Loki\CssUtils\Util\CssClass;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\Components\Component\ComponentViewModel;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Components\Util\Block\ImageRenderer;

/** @version 0.0.18 */
/** @var TemplateRenderer $templateRenderer */
/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ComponentViewModel $viewModel */
/** @var ImageRenderer $imageRenderer */
/** @var CssClass $css */

?>
<div class="<?= $escaper->escapeHtmlAttr($css('')) ?>">
    <p>Value: <span x-html="value"></span></p>

    <button
        @click="toggleModal"
        class="<?= $escaper->escapeHtmlAttr($css('btn btn-primary', 'button')) ?>"
        :disabled="isModalOpen"
    >
        <span x-cloak x-show="isModalOpen">Close Full Window Modal</span>
        <span x-show="isModalClosed">Open Full Window  Modal</span>
    </button>

    <dialog
        x-ref="modal"
        class="<?= $escaper->escapeHtmlAttr($css(
            'fullscreen border border-zinc-400 rounded-lg px-4 pb-4 w-full h-full',
            'dialog'
        )) ?>"
    >
        <div class="<?= $escaper->escapeHtmlAttr($css('w-full h-full p-4', 'dialog-inner')) ?>">
            <?= /* @noEscape */ $templateRenderer->html(
                $block, 'Loki_Components::component/modal/close.phtml'
            ) ?>

            <div class="<?= $escaper->escapeHtmlAttr($css('p-4 md:w-1/2 grid gap-4', 'dialog-inner')) ?>">
                <?= /* @noEscape */ $templateRenderer->html(
                    $block, 'YireoTraining_ExampleLokiComponents::modal/content.phtml'
                ) ?>

                <?= /* @noEscape */ $templateRenderer->html(
                    $block,
                    'Loki_Components::component/modal/close-button.phtml',
                    [
                        'label' => 'Close Full Window Modal'
                    ]
                ) ?>
            </div>
        </div>
    </dialog>
</div>
