<?php
declare(strict_types=1);

/** @version 0.0.10 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\Components\Component\ComponentViewModel;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Field\ViewModel\ImageOutput;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ComponentViewModel $viewModel */
/** @var ImageOutput */
$imageOutput = $viewModelFactory->create(ImageOutput::class);
?>
<div class="<?= $css('my-4', '@todo') ?>">
    <p>Value: <span x-html="value"></span></p>

    <button @click="toggleModal" class="<?= $css('btn btn-primary', '@todo') ?>" :disabled="isModalOpen">
        <span x-cloak x-show="isModalOpen">Close Full Window Modal</span>
        <span x-show="isModalClosed">Open Full Window  Modal</span>
    </button>

    <dialog x-ref="modal" class="<?= $css('border border-zinc-400 rounded-lg px-4 pb-4 w-full h-full', '@todo') ?>">
        <div class="<?= $css('w-full h-full', '@todo') ?>">
            <button @click="toggleModal" class="<?= $css('float-right cursor-pointer w-4', '@todo') ?>">
                <?= $escaper->escapeHtml($imageOutput->get('Loki_Components::images/xmark.svg')) ?>
            </button>

            <p class="<?= $css('my-4', '@todo') ?>">Input your text here</p>
            <input type="text" :value="value" @change="setValue" class="<?= $css('form-input', '@todo') ?>"/>

            <button @click="toggleModal" class="<?= $css('btn btn-primary mt-4', '@todo') ?>">
                <span>Close Full Window Modal</span>
            </button>
        </div>
    </dialog>
</div>
