<?php
declare(strict_types=1);

/** @version 0.0.10 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\Components\Component\ComponentViewModel;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Field\ViewModel\ImageOutput;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ComponentViewModel $viewModel */
/** @var ImageOutput */
$imageOutput = $viewModelFactory->create(ImageOutput::class);
?>
<div class="<?= /* noEscape */
/* @noEscape */
$css('my-4') ?>">
    <p>Value: <span x-html="value"></span></p>

    <button
        @click="toggleModal"
        class="<?= /* noEscape */
        /* @noEscape */
        $css('btn btn-primary', 'button') ?>"
        :disabled="isModalOpen"
    >
        <span x-cloak x-show="isModalOpen">Close Drawer Left</span>
        <span x-show="isModalClosed">Open Drawer Left</span>
    </button>

    <dialog
        x-ref="modal"
        class="<?= /* noEscape */
        /* @noEscape */
        $css('modal3 relative bg-inherit m-0 w-full h-full', 'dialog') ?>"
    >
        <div class="<?= /* noEscape */
        /* @noEscape */
        $css('bg-white w-1/2 h-full p-10', 'dialog-inner') ?>">
            <button
                @click="toggleModal"
                class="<?= /* noEscape */
                /* @noEscape */
                $css('float-right cursor-pointer w-4', 'dialog-button') ?>"
            >
                <?= $escaper->escapeHtml($imageOutput->get('Loki_Components::images/xmark.svg')) ?>
            </button>

            <p class="<?= /* noEscape */
            /* @noEscape */
            $css('my-4', 'dialog-content') ?>">
                Input your text here
            </p>

            <input
                type="text"
                :value="value"
                @change="setValue"
                class="<?= /* noEscape */
                /* @noEscape */
                $css('form-input', 'dialog-input') ?>"
            />

            <button
                @click="toggleModal"
                class="<?= /* noEscape */
                /* @noEscape */
                $css('btn btn-primary mt-4', 'dialog-button') ?>"
            >
                <span>Close Drawer</span>
            </button>
        </div>
    </dialog>

    <style>
        @keyframes modal3-dialog {
            from {
                left: -800px;
            }
            to {
                left: 0;
            }
        }

        .modal3[open] {
            animation: modal3-dialog 1s;
        }
    </style>
</div>

