<?php
declare(strict_types=1);

/** @version 0.0.14 */

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\Components\Component\ComponentViewModel;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Components\Util\ImageOutput;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ComponentViewModel $viewModel */
/** @var ImageOutput */
/** @var CssClass $css */

$imageOutput = $viewModelFactory->create(ImageOutput::class);
?>
<div class="<?= /* noEscape */
/* @noEscape */ $css('my-4') ?>">
    <p>Value: <span x-html="value"></span></p>

    <button
        @click="toggleModal"
        class="<?= /* noEscape */
        /* @noEscape */ $css('btn btn-primary', 'button') ?>"
        :disabled="isModalOpen"
    >
        <span x-cloak x-show="isModalOpen">Close Full Window Modal</span>
        <span x-show="isModalClosed">Open Full Window  Modal</span>
    </button>

    <dialog
        x-ref="modal"
        class="<?= /* noEscape */
        /* @noEscape */ $css('border border-zinc-400 rounded-lg px-4 pb-4 w-full h-full', 'dialog') ?>"
    >
        <div class="<?= /* noEscape */
        /* @noEscape */ $css('w-full h-full', 'dialog-inner') ?>">
            <button @click="toggleModal" class="<?= /* noEscape */
            /* @noEscape */ $css('float-right cursor-pointer w-4', 'close-button') ?>">
                <?= /* @noEscape */ $imageOutput->get('Loki_Components::images/xmark.svg') ?>
            </button>

            <p class="<?= /* noEscape */
            /* @noEscape */ $css('my-4', 'dialog-content') ?>">
                Input your text here
            </p>

            <input
                type="text"
                :value="value"
                @change="setValue"
                class="<?= /* noEscape */
            /* @noEscape */ $css('form-input', 'dialog-input') ?>"
            />

            <button
                @click="toggleModal"
                class="<?= /* noEscape */
            /* @noEscape */ $css('btn btn-primary mt-4', 'dialog-button') ?>"
            >
                <span>Close Full Window Modal</span>
            </button>
        </div>
    </dialog>
</div>
