<?php
declare(strict_types=1);

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\Components\Component\ComponentViewModel;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Components\Util\Block\ImageRenderer;

/** @version 0.0.14 */
/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ComponentViewModel $viewModel */
/** @var ImageRenderer $imageRenderer */
/** @var CssClass $css */


?>
<div class="<?= $escaper->escapeHtmlAttr($css('')) ?>">
    <p>Value: <span x-html="value"></span></p>

    <button
        @click="toggleModal"
        class="<?= $escaper->escapeHtmlAttr($css('btn btn-primary', 'button')) ?>"
        :disabled="isModalOpen"
    >
        <span x-cloak x-show="isModalOpen">Close Simple Modal</span>
        <span x-show="isModalClosed">Open Simple Modal</span>
    </button>

    <dialog
        x-ref="modal"
        class="<?= $escaper->escapeHtmlAttr($css('border border-zinc-400 rounded-lg p-4', 'dialog')) ?>"
    >
        <?= /* @noEscape */ $templateRenderer->html(
            $block, 'Loki_Components::component/modal/close.phtml'
        ) ?>

        <div class="<?= $escaper->escapeHtmlAttr($css('p-4 grid gap-4', 'dialog-inner')) ?>">
            <?= /* @noEscape */ $templateRenderer->html(
                $block, 'YireoTraining_ExampleLokiComponents::modal/content.phtml'
            ) ?>

            <?= /* @noEscape */ $templateRenderer->html(
                $block, 'Loki_Components::component/modal/close-button.phtml',
                [
                    'label' => 'Close Modal'
                ]
            ) ?>
        </div>
    </dialog>
</div>
