<?php
declare(strict_types=1);

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @version 0.0.14 */
/** @var CssClass $css */
/** @var Escaper $escaper */
/** @var Template $block */
?>
<div class="<?= $escaper->escapeHtmlAttr($css('my-4', )) ?>">
    Current template: <code><?= $escaper->escapeHtml($block->getTemplate()) ?></code>

    <button
        @click="toggle"
        class="<?= $escaper->escapeHtmlAttr($css('btn btn-primary', 'button')) ?>"
    >
        Switch to <code>example2.phtml</code>
    </button>
</div>
