<?php
declare(strict_types=1);

/** @version 0.0.12 */

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var CssClass $css */
/** @var Escaper $escaper */
/** @var Template $block */
?>
<div class="<?= /* @noEscape */ $css('my-4') ?>">
    Current template: <code><?= $escaper->escapeHtml($block->getTemplate()) ?></code>

    <button
        @click="toggle"
        class="<?= /* @noEscape */ $css('btn btn-primary', 'button') ?>"
    >
        Switch to <code>example1.phtml</code>
    </button>
</div>
