<?php
declare(strict_types=1);

/** @version 0.0.1 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
?>
<div class="<?= /* @noEscape */
$css('my-4', '@todo') ?>">
    Current template: <code><?= $escaper->escapeHtml($block->getTemplate()) ?></code>
    <button @click="toggle" class="<?= /* @noEscape */
$css('btn btn-primary', '@todo') ?>">
        Switch to <code>example1.phtml</code>
    </button>
</div>
