<?php
declare(strict_types=1);

/** @version 0.0.10 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use YireoTraining\ExampleLokiComponents\Component\Comments\CommentsViewModel;
use Loki\Components\Util\ComponentUtil;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var CommentsViewModel $viewModel */
/** @var ComponentUtil $componentUtil */
?>
<div class="<?= /* @noEscape */ $css('my-4', '@todo') ?>">
    <h3 class="<?= /* @noEscape */ $css('text-xl', '@todo') ?>">Existing Comments</h3>
    <ul>
        <?php foreach ($viewModel->getComments() as $comment) : ?>
            <li>
                <?= $escaper->escapeHtml($comment) ?>
                <button class="<?= /* @noEscape */ $css('btn w-3', '@todo') ?>" @click="remove" data-comment="<?= $escaper->escapeHtml($comment) ?>">x</button>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
