<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @version 0.0.17 */
/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('ExampleLokiComponentsComments', () => ({
            ...LokiComponentType,
            newComment: '',
            setNewComment(event) {
                this.newComment = event.target.value;
            },
            add(event) {
                this.post({
                    task: 'add',
                    comment: this.newComment
                });
                this.newComment = '';
            },
            remove(event) {
                this.post({
                    task: 'remove',
                    comment: event.target.getAttribute('data-comment')
                });
            }
        }));
    });
</script>
