<?php
declare(strict_types=1);

use Loki\Components\Component\ComponentViewModelInterface;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use YireoTraining\ExampleLokiComponents\Component\Comments\CommentsViewModel;
use Loki\Components\Util\ComponentUtil;

/** @version 0.0.14 */
/** @var ComponentViewModelInterface $viewModel */
/** @var Escaper $escaper */
/** @var Template $block */
/** @var CommentsViewModel $viewModel */
/** @var ComponentUtil $componentUtil */
?>
<div>
    Comments counter: <?= $escaper->escapeHtml(count($viewModel->getComments())) ?>
</div>
