<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Loki\CssUtils\Util\CssClass;
use Magento\Framework\View\Element\Template;

/** @version 0.0.15 */
/** @var Escaper $escaper */
/** @var CssClass $css */
/** @var Template $block */
?>
<div>
    <input
        aria-label="Comment text"
        x-text="newComment"
        @change="setNewComment" required
    />

    <button
        @click="add"
        class="<?= $escaper->escapeHtmlAttr($css('mt-4 btn btn-primary', 'button')) ?>"
    >Add comment</button>
</div>
