<?php
declare(strict_types=1);

/** @version 0.0.14 */

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var CssClass $cssUtil */
/** @var Escaper $escaper */
?>
Test linking to
<a href="<?php echo $escaper->escapeUrl($block->getUrl('customer/account')) ?>">
    <?php echo $block->escapeHtml(__('My Account')) ?>
</a>
