<?php
declare(strict_types=1);

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\View\Element\Template;
use Loki\Components\Util\Block\BlockRenderer;
use Loki\Components\Factory\ViewModelFactory;

/** @version 0.0.14 */
/** @var CssClass $css */
/** @var Template $block */
/** @var BlockRenderer $blockRenderer */
/** @var ViewModelFactory $viewModelFactory */

$notifications = [
    ['area' => 'js', 'type' => 'notice', 'text' => 'Global notice (JS)'],
    ['area' => 'js', 'type' => 'success', 'text' => 'Global success (JS)'],
    ['area' => 'js', 'type' => 'warning', 'text' => 'Global warning (JS)'],
    ['area' => 'js', 'type' => 'error', 'text' => 'Global error (JS)'],
    ['area' => 'global', 'type' => 'notice', 'text' => 'Global notice (PHP)'],
    ['area' => 'global', 'type' => 'success', 'text' => 'Global success (PHP)'],
    ['area' => 'global', 'type' => 'warning', 'text' => 'Global warning (PHP)'],
    ['area' => 'global', 'type' => 'error', 'text' => 'Global error (PHP)'],
    ['area' => 'local', 'type' => 'notice', 'text' => 'Local notice'],
    ['area' => 'local', 'type' => 'success', 'text' => 'Local success'],
    ['area' => 'local', 'type' => 'warning', 'text' => 'Local warning'],
    ['area' => 'local', 'type' => 'error', 'text' => 'Local error'],
];
?>
<div class="<?= /* @noEscape */ $css('my-4 grid grid-cols-4') ?>">
    <?php foreach ($notifications as $notification): ?>
    <button
        @click="notify"
        class="<?= $css('m-8 btn btn-color-[--button-'.$notification['type'].']') ?>"
        data-loki-area="<?= $notification['area'] ?>"
        data-loki-type="<?= $notification['type'] ?>"
        data-loki-text="<?= $notification['text'] ?>">
        <?= $notification['text'] ?>
        </button>
    <?php endforeach; ?>

    <?= /* @noEscape */ $blockRenderer->html($block, 'loki-components.utils.local-messages') ?>
</div>
