<?php
declare(strict_types=1);

/** @version 0.0.12 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('ExampleLokiComponentsNotify', () => ({
            ...LokiComponentType,
            notify(event) {
                const buttonElement = event.target;
                const area = buttonElement.getAttribute('data-loki-area');
                const type = buttonElement.getAttribute('data-loki-type');
                const text = buttonElement.getAttribute('data-loki-text');

                if (area === 'js') {
                    Alpine.store('LokiMessageStore').addMessage(type, text);
                    return;
                }

                this.post({
                    area: area,
                    type: type,
                    text: text,
                });
            }
        }));
    });
</script>
