<?php
declare(strict_types=1);

/** @version 0.0.10 */

use Magento\Framework\View\Element\Template;
use Loki\Components\Util\Block\BlockRenderer;
use Loki\Components\Factory\ViewModelFactory;

/** @var Template $block */
/** @var BlockRenderer $blockRenderer */
/** @var ViewModelFactory $viewModelFactory */
/** Tailwind classes: btn-error, btn-warning, btn-success, btn-notice */

$blockRenderer = $viewModelFactory->create(BlockRenderer::class);

$notifications = [
    ['area' => 'global', 'type' => 'notice', 'text' => 'Global notice'],
    ['area' => 'global', 'type' => 'success', 'text' => 'Global success'],
    ['area' => 'global', 'type' => 'warning', 'text' => 'Global warning'],
    ['area' => 'global', 'type' => 'error', 'text' => 'Global error'],
    ['area' => 'local', 'type' => 'notice', 'text' => 'Local notice'],
    ['area' => 'local', 'type' => 'success', 'text' => 'Local success'],
    ['area' => 'local', 'type' => 'warning', 'text' => 'Local warning'],
    ['area' => 'local', 'type' => 'error', 'text' => 'Local error'],
];
?>
<div class="<?= $css('my-4 grid grid-cols-4', '@todo') ?>">
    <?php foreach ($notifications as $notification): ?>
    <button
        @click="notify"
        class="m-8 btn btn-color-[--button-<?= $notification['type'] ?>]"
        data-loki-area="<?= $notification['area'] ?>"
        data-loki-type="<?= $notification['type'] ?>"
        data-loki-text="<?= $notification['text'] ?>">
        <?= $notification['text'] ?>
        </button>
    <?php endforeach; ?>

    <?= /* @noEscape */
$blockRenderer->html($block, 'loki-components.utils.local-messages') ?>
</div>
